
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# PostgreSQL specific settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# optional but recommended
spring.jpa.open-in-view=false



# JWT (custom properties)

app.jwt.secret=dev_secret_dev_secret_dev_secret_dev_secret_123456
app.jwt.access-exp-min=15
app.jwt.refresh-exp-days=7



#flyway

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

logging.level.org.flywaydb=DEBUG




# SWAGGER / OPENAPI(springdoc)

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# ACTUATOR (health check)

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# LOGGING

logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG